cause_mapping_list <- list(
  # 不專心
  Distraction = c(
    "起步時未注意安全",
    "恍神、緊張、心不在焉分心駕駛",
    "觀看其他事故、活動、道路環境或車外資訊分心駕駛",
    "飲食、抽(點)菸、拿(撿)物品分心駕駛",
    "穿越道路未注意左右來車",
    "橫越道路不慎",
    "乘客、車上動(生)物干擾分心駕駛",
    "操作、觀看行車輔助或娛樂性顯示設備",
    "使用手持行動電話"
  ),

  # 錯誤決策
  Decision = c(
    "違反閃光號誌",
    "車輛未依規定暫停讓行人先行",
    "其他不當駕車行為",
    "闖紅燈左轉(或迴轉)",
    "闖紅燈直行",
    "無號誌路口，轉彎車未讓直行車先行",
    "左轉彎未依規定",
    "逆向行駛",
    "無號誌路口，左方車未讓右方車先行",
    "右轉彎未依規定",
    "未依標誌或標線穿越道路",
    "未依規定減速",
    "閃避不當(慎)",
    "有號誌路口，轉彎車未讓直行車先行",
    "違反禁止超車標誌(線)",
    "變換車道不當",
    "倒車未依規定",
    "違反二段式左(右)轉標誌(線)",
    "無號誌路口，支線道未讓幹線道先行",
    "其他未依規定讓車",
    "未保持行車安全間隔",
    "未保持行車安全距離",
    "違反其他標誌(線)禁制",
    "迴轉未依規定",
    "未依號誌或手勢指揮(示)穿越道路",
    "超速駕駛",
    "違反其他號誌",
    "無號誌路口，少線道未讓多線道先行",
    "違規超車",
    "闖紅燈右轉",
    "違反禁止左轉、右轉標誌",
    "未避讓緊急任務車輛",
    "未避讓(跟隨、併駛、超車)消防、救護、警備、工程救險車、毒性化學物質災害事故應變車等執行緊急任務車",
    "未靠右行駛",
    "違反禁止變換車道標線",
    "爭(搶)道行駛",
    "未依規定行走地下道、天橋穿越道路",
    "多車道迴轉，未先駛入內側車道",
    "違反車輛專用標誌(線)",
    "違反遵行方向標誌(線)",
    "未依規定使用燈光",
    "違反禁止迴轉或迴車標誌",
    "行經圓環未依規定讓車",
    "未遵守依法令授權交通指揮人員之指揮",
    "山路會車，靠山壁車未讓外緣車先行",
    "違反行人專用標誌(線)",
    "違反車輛改道標誌",
    "違反禁止會車標誌",
    "車輛或機械操作不當(慎)",
    "方向不定(不包括危險駕車)",
    "搶(闖)越平交道",
    "違反禁行車種標誌(字)",
    "違反禁止進入標誌",
    "違反禁止各種車輛進入標誌"
  ),

  # 違規姿態 / 停車
  Posture = c(
    "違規(臨時)停車",
    "開啟或關閉車門不當",
    "未待乘客安全上下而開車",
    "車輛拋錨未採安全措施",
    "發生事故後，未採取安全措施",
    "暗處停車無燈光、標識",
    "車輛未停妥滑動致生事故",
    "停車操作時未注意安全",
    "上下車輛時未注意安全",
    "未待車輛停妥而上下車"
  ),

  # 酒駕 / 疲勞
  Driver_Impairment = c(
    "患病或服用藥物(疲勞)駕駛",
    "酒醉(後)駕駛",
    "打瞌睡或疲勞駕駛",
    "吸食違禁物駕駛",
    "打瞌睡或疲勞駕駛(包括連續駕車8小時)"
  ),

  # 其他
  Other = c(
    "在道路上嬉戲或奔走不定",
    "其他引起事故之疏失或行為",
    "峻狹坡路會車，下坡車未讓上坡車先行",
    "使用車輛自動駕駛或先進駕駛輔助系統設備(裝置)不符規定",
    "使用自動駕駛或先進駕駛輔助系統設備不符規定",
    "乘坐不當(慎)",
    "危險駕駛"
  ),

  # 車輛
  Vehicle = c(
    "車輪脫落或輪胎爆裂",
    "車輛零件脫落",
    "其他機件失靈或故障",
    "煞車失靈或故障",
    "裝載貨物不穩妥",
    "裝載未盡安全措施",
    "物品滾(滑行)或飛(掉)落",
    "車輛附屬機具或車門未盡安全措施",
    "方向操縱系統故障",
    "超載人員",
    "載運貨物超重",
    "裝卸貨物不當",
    "其他裝載不當",
    "燈光系統故障",
    "載運貨物超長、寬、高",
    "夜間行駛無燈光設備"
  ),

  # 環境
  Environmental = c(
    "在道路上工作之人員未設適當標識",
    "因光線、視線遮蔽致生事故",
    "道路設施、植栽或其他裝置倒塌或掉落",
    "施工安全防護措施未完善",
    "平交道看守疏失或未放柵欄",
    "強風、暴雨、濃霧(煙)",
    "動物竄出",
    "路況危險無安全(警告)設施",
    "未依法令授權指揮交通或指揮不當",
    "道路設施(備)、植栽或其他裝置，倒塌或掉(斷)落",
    "物品(件)滾(滑行)或飛(掉)落",
    "其他交通管制不當",
    "施工安全防護措施未依規定或未盡完善(備)"
  ),

  # 未發現 / 不明
  Unidentified = c(
    "尚未發現肇事因素",
    "相關跡證不足且無具體影像紀錄",
    "肇事逃逸未查獲，無法查明肇因",
    "事故發生時當事者逕自離開現場",
    "被車輛輾壓之不明物體彈飛",
    "相關跡證不足且無具體影像紀錄，當事人各執一詞，經分析後無法釐清肇事原因"
  )
)

col_translation_old <- c(
  "parkinglot_100m_count_mean" = "Parking lot count within 100m (mean)",
  "速限-第1當事者_mean" = "Speed limit – Party 1 (mean)",
  "車道劃分設施-分向設施大類別名稱_無" = "Lane division facility – directional separation (major category)_None",
  "車道劃分設施-分道設施-快車道或一般車道間名稱_車道線(無標記)" = "Lane Division Facility - Between Fast and General Lanes_Lane line (without marking)",
  "道路型態大類別名稱_交岔路" = "Road type (major category)_Intersection",
  "道路類別-第1當事者-名稱_市區道路" = "Road category – Party 1_Urban road",
  "道路類別-第1當事者-名稱_省道" = "Road category – Party 1_Provincial highway",
  "車道劃分設施-分道設施-路面邊線名稱_有" = "Lane Division Facility - Road Edge Line_Present",
  "車道劃分設施-分道設施-快車道或一般車道間名稱_未繪設車道線" = "Lane Division Facility - Between Fast and General Lanes_No lane line",
  "車道劃分設施-分道設施-快慢車道間名稱_快慢車道分隔線" = "Lane Division Facility - Between Fast and Slow Lanes_Dividing line",
  "號誌-號誌種類名稱_閃光號誌" = "Traffic signal type_Flashing signal",
  "車道劃分設施-分向設施大類別名稱_單向禁止超車線" = "Lane division facility – directional separation (major category)_One-way no-overtaking line",
  "事故類型及型態大類別名稱_車輛本身" = "Accident type and pattern (major category)_Vehicle itself",
  "道路類別-第1當事者-名稱_村里道路" = "Road category – Party 1_Village road",
  "車道劃分設施-分道設施-快慢車道間名稱_窄式快慢車道分隔島(附柵欄)" = "Lane Division Facility - Between Fast and Slow Lanes_Narrow-type divider island (with barrier)",
  "車道劃分設施-分道設施-快慢車道間名稱_窄式快慢車道分隔島(無柵欄)" = "Lane Division Facility - Between Fast and Slow Lanes_Narrow-type divider island (without barrier)",
  "車道劃分設施-分道設施-快車道或一般車道間名稱_車道線(附標記)" = "Lane Division Facility - Between Fast and General Lanes_Lane line (with marking)",
  "道路類別-第1當事者-名稱_國道" = "Road category – Party 1_National highway",
  "道路類別-第1當事者-名稱_專用道路" = "Road category – Party 1_Exclusive road",
  "道路類別-第1當事者-名稱_鄉道" = "Road category – Party 1_Township road",
  "道路型態大類別名稱_單路部分" = "Road type (major category)_Single road section",
  "事故類型及型態大類別名稱_車與車" = "Accident type and pattern (major category)_Vehicle-to-vehicle",
  "車道劃分設施-分向設施大類別名稱_行車分向線" = "Lane division facility – directional separation (major category)_Directional line",
  "號誌-號誌種類名稱_無號誌" = "Traffic signal type_No signal",
  "車輛撞擊部位大類別名稱-最初_其他" = "Vehicle impact location (major category, initial)_Other",
  "車輛撞擊部位大類別名稱-最初_機車與自行車" = "Vehicle impact location (major category, initial)_Motorcycle/Bicycle",
  "號誌-號誌種類名稱_行車管制號誌" = "Traffic signal type_Traffic control signal",
  "車道劃分設施-分道設施-快車道或一般車道間名稱_禁止變換車道線(無標記)" = "Lane Division Facility - Between Fast and General Lanes_No-lane-change line (without marking)",
  "車道劃分設施-分向設施大類別名稱_中央分向島" = "Lane division facility – directional separation (major category)_Central divider island",
  "事故類型及型態大類別名稱_人與車" = "Accident type and pattern (major category)_Person vs vehicle",
  "車輛撞擊部位大類別名稱-最初_汽車" = "Vehicle impact location (major category, initial)_Automobile",
  "道路類別-第1當事者-名稱_其他" = "Road category – Party 1_Other",
  "道路型態大類別名稱_其他" = "Road type (major category)_Other",
  "號誌-號誌種類名稱_行車管制號誌(附設行人專用號誌)" = "Traffic signal type_Traffic control signal (with pedestrian-only signal)",
  "車道劃分設施-分道設施-快車道或一般車道間名稱_禁止變換車道線(附標記)" = "Lane Division Facility - Between Fast and General Lanes_No-lane-change line (with marking)",
  "車道劃分設施-分道設施-快慢車道間名稱_未繪設快慢車道分隔線" = "Lane Division Facility - Between Fast and Slow Lanes_No lane line",
  "車道劃分設施-分道設施-路面邊線名稱_無" = "Lane Division Facility - Road Edge Line_Not present",
  "車道劃分設施-分道設施-快慢車道間名稱_寬式快慢車道分隔島(50公分以上)" = "Lane Division Facility - Between Fast and Slow Lanes_Wide-type divider island (≥50 cm)",
  "車道劃分設施-分向設施大類別名稱_雙向禁止超車線" = "Lane division facility – directional separation (major category)_Two-way no-overtaking line",
  "道路類別-第1當事者-名稱_縣道" = "Road category – Party 1_County road",
  "事故類型及型態大類別名稱_平交道事故" = "Accident type and pattern (major category)_Level crossing accident",
  "道路型態大類別名稱_平交道" = "Road type (major category)_Level crossing",
  "youbike_100m_count_mean" = "YouBike station count within 100m (mean)",
  "道路類別-第1當事者-名稱_快速(公)道" = "Road category – Party 1_Expressway",
  "道路型態大類別名稱_圓環廣場" = "Road type (major category)_Roundabout/Plaza",
  "mrt_100m_count_mean" = "MRT station count within 100m (mean)",
  "當事者區分-類別-大類別名稱-車種_大客車" = "Party category – Vehicle type_Large bus",
  "當事者區分-類別-大類別名稱-車種_小貨車" = "Party category – Vehicle type_Small truck",
  "當事者區分-類別-大類別名稱-車種_全聯結車" = "Party category – Vehicle type_Full trailer truck",
  "當事者區分-類別-大類別名稱-車種_其他車" = "Party category – Vehicle type_Other vehicle",
  "當事者區分-類別-大類別名稱-車種_軍車" = "Party category – Vehicle type_Military vehicle",
  "當事者區分-類別-大類別名稱-車種_特種車" = "Party category – Vehicle type_Special-purpose vehicle",
  "當事者區分-類別-大類別名稱-車種_小貨車(含客、貨兩用)" = "Party category – Vehicle type_Small truck (incl. passenger/cargo)",
  "當事者區分-類別-大類別名稱-車種_小客車(含客、貨兩用)" = "Party category – Vehicle type_Passenger car (incl. passenger/cargo)",
  "當事者區分-類別-大類別名稱-車種_半聯結車" = "Party category – Vehicle type_Semi-trailer truck",
  "當事者區分-類別-大類別名稱-車種_機車" = "Party category – Vehicle type_Motorcycle",
  "當事者區分-類別-大類別名稱-車種_曳引車" = "Party category – Vehicle type_Tractor unit",
  "當事者區分-類別-大類別名稱-車種_慢車" = "Party category – Vehicle type_Slow-moving vehicle",
  "當事者區分-類別-大類別名稱-車種_人" = "Party category – Vehicle type_Pedestrian",
  "當事者區分-類別-大類別名稱-車種_大貨車" = "Party category – Vehicle type_Heavy truck"
)

col_translation <- c(
  "parkinglot_100m_count_mean" = "Parking lot count within 100m",
  "速限-第1當事者_mean" = "Speed limit",
  "車道劃分設施-分向設施大類別名稱_無" = "directional separation_None",
  "車道劃分設施-分道設施-快車道或一般車道間名稱_車道線(無標記)" = "Between Fast and General Lanes_Lane line (without marking)",
  "道路型態大類別名稱_交岔路" = "Road type_Intersection",
  "道路類別-第1當事者-名稱_市區道路" = "Road category_Urban road",
  "道路類別-第1當事者-名稱_省道" = "Road category_Provincial highway",
  "車道劃分設施-分道設施-路面邊線名稱_有" = "Road Edge Line_Present",
  "車道劃分設施-分道設施-快車道或一般車道間名稱_未繪設車道線" = "Between Fast and General Lanes_No lane line",
  "車道劃分設施-分道設施-快慢車道間名稱_快慢車道分隔線" = "Between Fast and Slow Lanes_Dividing line",
  "號誌-號誌種類名稱_閃光號誌" = "Traffic signal type_Flashing signal",
  "車道劃分設施-分向設施大類別名稱_單向禁止超車線" = "directional separation_One-way no-overtaking line",
  "事故類型及型態大類別名稱_車輛本身" = "Accident type and pattern_Vehicle itself",
  "道路類別-第1當事者-名稱_村里道路" = "Road category_Village road",
  "車道劃分設施-分道設施-快慢車道間名稱_窄式快慢車道分隔島(附柵欄)" = "Between Fast and Slow Lanes_Narrow-type divider island (with barrier)",
  "車道劃分設施-分道設施-快慢車道間名稱_窄式快慢車道分隔島(無柵欄)" = "Between Fast and Slow Lanes_Narrow-type divider island (without barrier)",
  "車道劃分設施-分道設施-快車道或一般車道間名稱_車道線(附標記)" = "Between Fast and General Lanes_Lane line (with marking)",
  "道路類別-第1當事者-名稱_國道" = "Road category_National highway",
  "道路類別-第1當事者-名稱_專用道路" = "Road category_Exclusive road",
  "道路類別-第1當事者-名稱_鄉道" = "Road category_Township road",
  "道路型態大類別名稱_單路部分" = "Road type_Single road section",
  "事故類型及型態大類別名稱_車與車" = "Accident type and pattern_Vehicle-to-vehicle",
  "車道劃分設施-分向設施大類別名稱_行車分向線" = "directional separation_Directional line",
  "號誌-號誌種類名稱_無號誌" = "Traffic signal type_No signal",
  "車輛撞擊部位大類別名稱-最初_其他" = "Vehicle impact location_Other",
  "車輛撞擊部位大類別名稱-最初_機車與自行車" = "Vehicle impact location_Motorcycle/Bicycle",
  "號誌-號誌種類名稱_行車管制號誌" = "Traffic signal type_Traffic control signal",
  "車道劃分設施-分道設施-快車道或一般車道間名稱_禁止變換車道線(無標記)" = "Between Fast and General Lanes_No-lane-change line (without marking)",
  "車道劃分設施-分向設施大類別名稱_中央分向島" = "directional separation_Central divider island",
  "事故類型及型態大類別名稱_人與車" = "Accident type and pattern_Person vs vehicle",
  "車輛撞擊部位大類別名稱-最初_汽車" = "Vehicle impact location_Automobile",
  "道路類別-第1當事者-名稱_其他" = "Road category_Other",
  "道路型態大類別名稱_其他" = "Road type_Other",
  "號誌-號誌種類名稱_行車管制號誌(附設行人專用號誌)" = "Traffic signal type_Traffic control signal (with pedestrian-only signal)",
  "車道劃分設施-分道設施-快車道或一般車道間名稱_禁止變換車道線(附標記)" = "Between Fast and General Lanes_No-lane-change line (with marking)",
  "車道劃分設施-分道設施-快慢車道間名稱_未繪設快慢車道分隔線" = "Between Fast and Slow Lanes_No lane line",
  "車道劃分設施-分道設施-路面邊線名稱_無" = "Road Edge Line_Not present",
  "車道劃分設施-分道設施-快慢車道間名稱_寬式快慢車道分隔島(50公分以上)" = "Between Fast and Slow Lanes_Wide-type divider island (≥50 cm)",
  "車道劃分設施-分向設施大類別名稱_雙向禁止超車線" = "directional separation_Two-way no-overtaking line",
  "道路類別-第1當事者-名稱_縣道" = "Road category_County road",
  "事故類型及型態大類別名稱_平交道事故" = "Accident type and pattern_Level crossing accident",
  "道路型態大類別名稱_平交道" = "Road type_Level crossing",
  "youbike_100m_count_mean" = "YouBike station count within 100m",
  "道路類別-第1當事者-名稱_快速(公)道" = "Road category_Expressway",
  "道路型態大類別名稱_圓環廣場" = "Road type_Roundabout/Plaza",
  "mrt_100m_count_mean" = "MRT station count within 100m",
  "當事者區分-類別-大類別名稱-車種_大客車" = "Party – Vehicle type_Large bus",
  "當事者區分-類別-大類別名稱-車種_小貨車" = "Party – Vehicle type_Small truck",
  "當事者區分-類別-大類別名稱-車種_全聯結車" = "Party – Vehicle type_Full trailer truck",
  "當事者區分-類別-大類別名稱-車種_其他車" = "Party – Vehicle type_Other vehicle",
  "當事者區分-類別-大類別名稱-車種_軍車" = "Party – Vehicle type_Military vehicle",
  "當事者區分-類別-大類別名稱-車種_特種車" = "Party – Vehicle type_Special-purpose vehicle",
  "當事者區分-類別-大類別名稱-車種_小貨車(含客、貨兩用)" = "Party – Vehicle type_Small truck (incl. passenger/cargo)",
  "當事者區分-類別-大類別名稱-車種_小客車(含客、貨兩用)" = "Party – Vehicle type_Passenger car (incl. passenger/cargo)",
  "當事者區分-類別-大類別名稱-車種_半聯結車" = "Party – Vehicle type_Semi-trailer truck",
  "當事者區分-類別-大類別名稱-車種_機車" = "Party – Vehicle type_Motorcycle",
  "當事者區分-類別-大類別名稱-車種_曳引車" = "Party – Vehicle type_Tractor unit",
  "當事者區分-類別-大類別名稱-車種_慢車" = "Party – Vehicle type_Slow-moving vehicle",
  "當事者區分-類別-大類別名稱-車種_人" = "Party – Vehicle type_Pedestrian",
  "當事者區分-類別-大類別名稱-車種_大貨車" = "Party – Vehicle type_Heavy truck"
)
